apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-metrics
  namespace: storm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: gateway-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
