apiVersion: 1

# ─────────────────────────────────────────────────────────────────
# Contact Points — où envoyer les alertes
# Les URLs sont injectées via variables d'environnement :
#   SLACK_WEBHOOK_URL   → webhook Slack (Incoming Webhooks app)
#   DISCORD_WEBHOOK_URL → webhook Discord (channel settings > Integrations)
# ─────────────────────────────────────────────────────────────────

contactPoints:

  # Slack — alertes critiques (ServiceDown, PodCrashLooping)
  - orgId: 1
    name: Slack Critical
    receivers:
      - uid: slack-critical
        type: slack
        disableResolveMessage: false
        settings:
          url: ${SLACK_WEBHOOK_URL}
          title: |
            [{{ .Status | toUpper }}{{ if eq .Status "firing" }} 🔥{{ else }} ✅{{ end }}] STORM — {{ .CommonLabels.alertname }}
          text: |
            {{ range .Alerts }}
            *{{ .Annotations.summary }}*
            {{ if .Annotations.description }}{{ .Annotations.description }}{{ end }}
            Severity: `{{ .Labels.severity }}`
            {{ end }}
          username: STORM Alerts
          icon_emoji: ":warning:"

  # Discord — toutes les alertes (warning + critical)
  - orgId: 1
    name: Discord Alerts
    receivers:
      - uid: discord-alerts
        type: discord
        disableResolveMessage: false
        settings:
          url: ${DISCORD_WEBHOOK_URL}
          message: |
            **[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}**
            {{ range .Alerts -}}
            > {{ .Annotations.summary }}
            {{ if .Annotations.description }}{{ .Annotations.description }}{{ end }}
            Sévérité : **{{ .Labels.severity }}**
            {{ end }}

---
apiVersion: 1

# ─────────────────────────────────────────────────────────────────
# Notification Policies — qui reçoit quoi
# ─────────────────────────────────────────────────────────────────

policies:
  - orgId: 1
    receiver: Discord Alerts        # récepteur par défaut (toutes les alertes)
    group_by: ['alertname', 'severity']
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
    routes:
      # Alertes critiques → Slack ET Discord
      - receiver: Slack Critical
        matchers:
          - severity = critical
        continue: true              # continue = aussi envoyé à Discord via default

      # Warnings → Discord uniquement (pas de Slack pour ne pas spammer)
      - receiver: Discord Alerts
        matchers:
          - severity = warning
