apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-metrics
  namespace: storm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: gateway-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: user-metrics
  namespace: storm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: user-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: message-metrics
  namespace: storm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: message-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: media-metrics
  namespace: storm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: media-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: notification-metrics
  namespace: storm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: notification-service
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nats-exporter-metrics
  namespace: storm
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: nats-exporter
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
